# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
name: 三晋的Blog
title: 三晋的Blog
email: majinshou@gmail.com
url: "https//majinshou.github.io" # the base hostname & protocol for your site
description: 曾经有一个绝好的赚钱机会摆在我面前，我没有珍惜，如果上天能够再给我一次机会的话……<br/>我依然这么尿性，不服，你咬我啊！^0^
github_username:  majinshou
encoding: UTF-8

# Build settings
markdown: kramdown
