# Site settings
name: Welcome to HuluCat'sBlog
title: Welcome to HuluCat's Blog
email: majinshou@gmail.com
url: "https//majinshou.github.io" # the base hostname & protocol for your site
description: Goals determine what you’re going to be.
github_username: majinshou
encoding: UTF-8

# Build settings
markdown: kramdown
