# Site settings
name: Welcome to Actto'sBlog
title: Welcome to Actto's Blog
email: majinshou@gmail.com
url: "http//www.majinshou.cn" # the base hostname & protocol for your site
description: Goals determine what you’re going to be.
github_username: acttos
encoding: UTF-8

# Build settings
markdown: kramdown
