# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
name: 三晋的Blog
title: 三晋的Blog
email: majinshou@gmail.com
url: "https//majinshou.github.io" # the base hostname & protocol for your site
description: 不积跬步，无以至千里；不积小流，无以成江海。
github_username:  majinshou
encoding: UTF-8

# Build settings
markdown: kramdown
